//词贴管理
const manageWidget = {
	addGroup: 'New Group',
	groupName_max_words_four: 'Group name; no more than 4 chars',
	rename_group: 'Rename',
	add_folder: 'New Folder',
	confirm: 'Confirm',
	cancel: 'Cancel',
	confirm_del_this_item: 'Confirm to delete the item?',
	'delete': 'Delete',
	moveTo: 'Move to',
	save: 'Save',
	deleteService: 'Delete',
	confirm_delete_this_service: 'Confirm to delete the service?',
	move: 'Move',
	group: 'Group',
	to: 'To',
	notSave: 'Discard',
	confirm_to_delete_batch: 'Confirm to batch delete?',
	notSave_to_lose_new_modify: 'Click Discard and the latest modifications will be discarded',
	addQuick_to_home: 'Add Shortcut to Homepage',
	all: 'All',
	search: 'Search',
	add: 'Add',
	searchContent: 'Search...',
	added: 'Added',
	notAdd: 'Not Added',
	extend: 'Expand',
	unfold: 'Hide',
	rename_folder: 'Rename',
	delete_folder: 'Delete',
	confirm_delete_service: 'Confirm to delete the service?',
	group_name_exists: 'Group name already exists',
	move_down: 'Move Down',
	move_up: 'Move Up',
	more: 'More',
	save_latest_or_not: 'Save the latest modification?',
	noDataGroup: 'The groups without content are invisible on homepage',
	notice: 'Drag the widgets below to the right',
	inputServiceName:'Please enter service name ',
    noData:'No data',	
};

export default {
	...manageWidget
}
