//词贴管理
const manageWidget = {
	addGroup: '添加分組',
	groupName_max_words_four: '分組名稱,最多4個字元',
	rename_group: '重命名分組',
	add_folder: '添加檔夾',
	confirm: '確認',
	cancel: '取消',
	confirm_del_this_item: '您確認要刪除此項？',
	'delete': '刪除',
	moveTo: '移動到',
	save: '保存',
	deleteService: '刪除服務',
	confirm_delete_this_service: '您確認要刪除此項服務？',
	move: '移動',
	group: '分組',
	to: '到',
	notSave: '不保存',
	confirm_to_delete_batch: '您確認要批量刪除嗎？',
	notSave_to_lose_new_modify: '點擊不保存，則最新修改將丟失',
	addQuick_to_home: '添加快捷方式至首頁',
	all: '全部',
	search: '搜索',
	add: '添加',
	searchContent: '搜索內容...',
	added: '已添加',
	notAdd: '未添加',
	extend: '展開',
	unfold: '收起',
	rename_folder: '重命名檔夾',
	delete_folder: '刪除檔夾',
	confirm_delete_service: '您確認要刪除服務',
	group_name_exists: '分組名稱已存在！',
	move_down: '下移',
	move_up: '上移',
	more: '更多',
	save_latest_or_not: '是否保存最新修改？',
	noDataGroup: '無內容的分組在首頁不可見',
	notice: '拖動下方磁貼至右側所需位置',
	inputServiceName:'輸入服務名稱',
    noData:'暫無結果',	
};

export default {
	...manageWidget
}
