import { createActions } from '@u';
import types from './types';
import {
  getUserInfo,
  uploadApplication,
  getPoll,
  setCurrent,
  getAllEnable,
  getCurrent,
  setCurrentNot,
  getAllEnableNot,
  getCurrentNot,
  getDefaultDesktop,
  setDefaultDesktop,
  getCurrentDate,
  setCurrentDate,
	setTheme,
	getHelpManage,
} from './api';

const {
  REQUEST_START,
  REQUEST_SUCCESS,
  REQUEST_ERROR,
  GET_USER_INFO,
  SET_USER_INFO,
  CHANGE_QUICK_SERVICE_DISPLAY,
  CHANGE_QUICK_SERVICE_HIDDEN,
  CHANGE_MESSAGE_TYPE,
  UPDATE_GROUP_IM,
  UN_READED_IM,
  SHOW_IM,
  HIDE_IM,
  UPLOAD_APPLICATION,
  GET_POLL,
  SET_CURRENT,
  GET_ALL_ENABLE,
  GET_CURRENT,
  SET_CURRENT_NOT,
  GET_ALL_ENABLE_NOT,
  GET_CURRENT_NOT,
  SHOW_DIALOG,
  CLOSE_DIALOG_NEW,
  OPEN_FRAME,
  CLOSE_FRAME,
  GET_DEFAULT_DESKTOP,
  SET_DEFAULT_DESKTOP,
  GET_CURRENT_DATE,
  SET_CURRENT_DATE,
	SET_THEME,
	GET_HELP_MANAGE,
} = types;

export default createActions(
  {
    [GET_USER_INFO]: getUserInfo,
    [UPLOAD_APPLICATION]: uploadApplication,
    [GET_POLL]: getPoll,
    [SET_CURRENT]: setCurrent,
    [GET_ALL_ENABLE]: getAllEnable,
    [GET_CURRENT]: getCurrent,
    [SET_CURRENT_NOT]: setCurrentNot,
    [GET_ALL_ENABLE_NOT]: getAllEnableNot,
    [GET_CURRENT_NOT]: getCurrentNot,
    [GET_DEFAULT_DESKTOP]:getDefaultDesktop,
    [SET_DEFAULT_DESKTOP]:setDefaultDesktop,
    [GET_CURRENT_DATE]: getCurrentDate,
    [SET_CURRENT_DATE]: setCurrentDate,
		[SET_THEME]: setTheme,
		[GET_HELP_MANAGE]: getHelpManage,
  },
  REQUEST_START,
  REQUEST_SUCCESS,
  REQUEST_ERROR,
  SET_USER_INFO,
  CHANGE_QUICK_SERVICE_DISPLAY,
  CHANGE_QUICK_SERVICE_HIDDEN,
  CHANGE_MESSAGE_TYPE,
  UPDATE_GROUP_IM,
  UN_READED_IM,
  SHOW_IM,
  HIDE_IM,
  SHOW_DIALOG,
  CLOSE_DIALOG_NEW,
  OPEN_FRAME,
  CLOSE_FRAME,
);
