import { createActions } from '@u';
import types from './types';
import {
  getServiceList,
  getPortal,
  cancelFolders,
  setFolders,
  addFolders,
  getAllMenuList,
  getHistoryList,
  setLeadStatus,
  getAllPortal,
	setDefaultPortal,
} from './api';

const {
  GET_SERVICE_LIST,
  GET_PORTAL,
  OPEN_ROOT,
  OPEN_PORTAL,
  SHOW_TABS,
  ADD_TABS,
  DEL_TABS,
  CLOSE_TABS,
  UPDATE_TABS,
  OPEN_PIN,
  CLOSE_PIN,
  CANCEL_FOLDERS,
  SET_FOLDERS,
  ADD_FOLDERS,
  GET_ALL_MENU_LIST,
  GET_HISTORY_LIST,
  CHANGE_RETRACT,
  SET_MENU_KEYS,
  SET_LEAD_STATUS,
  RECORD_SERVICE_INFO,
  GET_ALL_PORTAL,
	SET_DEFAULT_PORTAL,
} = types;

export default createActions(
  {
    namespace: 'wrap',
  },
  {
    [GET_SERVICE_LIST]: getServiceList,
    [GET_PORTAL]: getPortal,
    [CANCEL_FOLDERS]: cancelFolders,
    [SET_FOLDERS]: setFolders,
    [ADD_FOLDERS]: addFolders,
    [GET_ALL_MENU_LIST]: getAllMenuList,
    [GET_HISTORY_LIST]: getHistoryList,
    [SET_LEAD_STATUS]: setLeadStatus,
    [GET_ALL_PORTAL]:getAllPortal,
		[SET_DEFAULT_PORTAL]:setDefaultPortal,
  },
  OPEN_ROOT,
  OPEN_PORTAL,
  SHOW_TABS,
  ADD_TABS,
  DEL_TABS,
  CLOSE_TABS,
  UPDATE_TABS,
  OPEN_PIN,
  CLOSE_PIN,
  CHANGE_RETRACT,
  SET_MENU_KEYS,
  RECORD_SERVICE_INFO,
);
